database:
  url: jdbc:mysql://localhost:3306/orderdb
  username: root
  password: root
  timeout: 6
  pool:
    max-size: 10
    min-size: 5
  servers:
    - server1
    - server2
    - server3
  roles:
    admin: ADMIN
    user: USER


#kafka properties
spring:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"


