spring.application.name=Springboot_mongodb

spring.data.mongodb.uri=mongodb+srv://pradipemployee007_db_user:hdDAcY6m7bbM6eD@cluster0.7dcuixl.mongodb.net/sample_mflix?retryWrites=true&w=majority
#spring.data.mongodb.database=sample_mflix
