spring.application.name=Springboot_mongodb
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=companyDB
spring.data.mongodb.uri=mongodb+srv://pradipemployee007_db_user:hdDAcY6m7bbM6eD@cluster0.q6ypgax.mongodb.net/?appName=Cluster0
#logging.level.org.springframework.data.mongodb=DEBUG
#logging.level.org.mongodb.driver=DEBUG